### ISSUE TITLE
Icon Firefox pas assez visible

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/extensions-notificateurs#24]
On ne voit pas qu'on une notification, il faudrait du rouge comme sur le site !

**Comment by AmarOk1412** [comment]
@gustavi je n'ai pas encore changé ce point. Mais je viens de rajouter les notifications de bureaux si tu souhaite tester : https://github.com/zestedesavoir/extensions-notificateurs/pull/28

**Comment by gustavi** [comment]
J'essaye de tester ça rapidement !
