### ISSUE TITLE
Chrome Tailor ?

### ISSUE THREAD

**Issue by viki53** [zestedesavoir/extensions-notificateurs#33]
Je viens de tomber sur [cet article de Korben](http://korben.info/chrome-tailor-convertir-des-extensions-chrome-en-extensions-firefox.html) et je me suis dit que ça pourrait être une façon simple de maintenir l'extension Firefox avec une seule base de code, non ?

Après j'ai plus les API en tête, mais de mémoire on en utilise pas énormément, si ?

Poke @AmarOk1412 @Eskimon

**Comment by AmarOk1412** [comment]
Je vais dire comme Korben  : À tester... :)
Mais je suis plutôt pour.

**Comment by AmarOk1412** [comment]
Je ferme, la version WebExtensions permettant de ne maintenir qu'une seule base de code :)
