### ISSUE TITLE
Firefox 13 : l'extension n'est plus acceptée par Firefox

### ISSUE THREAD

**Issue by Deuchnord** [zestedesavoir/extensions-notificateurs#34]
Hello,

Je ne sais pas si les extensions sont toujours maintenues, mais aujourd'hui j'ai eu droit à une petite surprise de la part de Firefox :

![zds-notif n'a pas pu être érifié pour son utilisation dans Firefox et a été désactivé](https://cloud.githubusercontent.com/assets/7600265/11850480/cf81aaa0-a42d-11e5-9f56-8446617f033a.png)

Apparemment, c'est lié au fait que l'extension n'est pas signée. Firefox propose bien un moyen de la réactiver, mais il faut pour ça désactiver totalement la protection contre les extensions non signées dans `about:config`, ce qui n'est pas forcément idéal…

**Comment by AmarOk1412** [comment]
Ouai faut que refasse l'extension, c'est sur ma todo list. Et je vais faire la signature avec :). J'essaye de faire ça pour la fin de l'année :)

**Comment by Deuchnord** [comment]
D'accord, bon courage ^^

**Comment by roipoussiere** [comment]
Ça en est où ?  J'aimerais bien utiliser cette extension sur Firefox. :-) Il y a des infos [ici](https://developer.mozilla.org/en-US/Add-ons/Distribution) concernant la signature de l'application.

**Comment by viki53** [comment]
La PR #41 est un refactor complet pour utiliser les WebExtensions, dès que ce sera fini et mergé, ça devrait être dispo sur Firefox et Chrome. ;)

**Comment by roipoussiere** [comment]
Ah super, excellent !

En attendant j'ai accepté les addons non signés.
