### ISSUE TITLE
Sur opera

### ISSUE THREAD

**Issue by Eragonfr** [zestedesavoir/extensions-notificateurs#52]
Salut je signale que je n'ai pas réussi a installer cette extension sur opera a cause d'un fichier manifest invalide ou inexistant

**Comment by AmarOk1412** [comment]
@Eragonfr je pense que personne n'a pensé à le tester sur Opera. Si Opéra gère les webextensions, alors ça devrait être possible de le porter assez facilement, mais en soit il n'y a que l'extension sur Chrome et Firefox pour le moment.

**Comment by Eragonfr** [comment]
En fait normalement opera gère les webextensions de chrome et celles du [store d'opera](https://addons.opera.com/fr/) mais apparemment cette fois-ci il y a une erreur

**Comment by AmarOk1412** [comment]
tu as testé avec quelle extension ? Si c'est celle du chrome store, vu qu'elle est pas encore en webextensions (ma PR est encore ouverte), ça ne marchera pas.

**Comment by Eragonfr** [comment]
Ok mais j'ai essayé avec le code source directement et ça n'a pas marché non plus

**Comment by Eragonfr** [comment]
C'est réussi mais je m'était trompé en chargeant l'extension mais maintenant j'ai une erreur dans le code. Je sait jamais si il faut fermer cette issue et en ouvrir une autre pour l'erreur ou si il faut donner l'erreur dans cette issue.

**Comment by motet-a** [comment]
Tu peux continuer ici :)

**Comment by Eragonfr** [comment]
je sait pas exactement si l'erreur est du à ZdS ou si c'est l'extension qui bug mais je vais la donner
les message d'erreur dans la console de débogage
![console01](https://user-images.githubusercontent.com/28783835/32994865-d92eb5ba-cd6c-11e7-9457-47422bcd4dd7.png)
![console02](https://user-images.githubusercontent.com/28783835/32994866-d94c8c84-cd6c-11e7-8c38-77602bca74e2.png)
et le statut du network
![network](https://user-images.githubusercontent.com/28783835/32994867-d96a48fa-cd6c-11e7-99c6-7e4b2fb7097b.png)

**Comment by motet-a** [comment]
@Eragonfr Merci beaucoup ! En effet, c’est pas propre à l’extension. Je signale ça tout de suite, ça devrait être corrigé assez vite.

**Comment by motet-a** [comment]
@Eragonfr Normalement ça vient juste d’être (déjà) corrigé. Tu peux nous confirmer que tout est bon de ton côté (en tout cas tu ne devrais plus avoir de 405) ?

**Comment by Eragonfr** [comment]
J'ai plus d'erreur mais je suis déconnecté

**Comment by Eragonfr** [comment]
Et pourtant je suis connecté sur ZdS

**Comment by Eragonfr** [comment]
Résolu en ré-installant zds-notificateur via le chrome-web-store
