### ISSUE TITLE
Double barre oblique dans les liens

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/extensions-notificateurs#53]
Je viens de recevoir une notification avec deux barres obliques dans le lien : 

```
https://zestedesavoir.com//billets/2173/le-premier-jour-du-reste-de-ma-vie/?page=1#p167009
```

Le lien fonctionne toujours (au moins sur Firefox desktop mais je suppose que c'est pareil sur la majorité des navigateurs) donc ce n'est pas bloquant mais c'est à corriger :)

**Comment by AmarOk1412** [comment]
aha Joli @Situphen thx !

**Comment by vhf** [comment]
> Le lien fonctionne toujours (au moins sur Firefox desktop mais je suppose que c'est pareil sur la majorité des navigateurs) 

C'est une URI valide, et le serveur la traitera toujours sans problème en servant le contenu de `/foo` quand on lui demande `//foo`. ;) (Ça peut poser problème sur des choses pas utilisées ici, le navigateur traitant à raison `/foo` et `//foo` comme des URLs différentes.)

**Comment by AmarOk1412** [comment]
Dans tous les cas, ce n'est pas propre.

**Comment by AmarOk1412** [comment]
Fixé en 2.6
